server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false           # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 5000       # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
  client:
    service-url:
      default-zone: http://localhost:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true                   #服务注册方式  IP地址
    instance-id: ${spring.cloud.client.ipAddress}:${random.int}  # 服务的id