server:
  port: 8203

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true                   #服务注册方式  IP地址
    instance-id: ${spring.cloud.client.ipAddress}:${random.int}  # 服务的id
spring:
  application:
    name: hour-service
  zipkin:
    base-url: http://localhost:9411
