Configuration:
  status: info

  Properties:
    Property:
      -  name: logFormat
         value: '%d{yyyy-MM-dd HH:mm:ss.SSS}{GMT+8} [vehicle-server] [%thread] %-5level %logger{35} - %msg %n'
      -  name: kafkaBootstrapServers
         value: 114.215.80.37:9092

  Appenders:
    Console:  #输出到控制台
      name: Console
      target: SYSTEM_OUT
      ThresholdFilter:
        level: trace
        onMatch: ACCEPT
        onMismatch: DENY
      PatternLayout:
        pattern: ${logFormat}

    Kafka: #输出到Kafka
      name: Kafka
      topic:  test
      ThresholdFilter:
        level: info
        onMatch: ACCEPT
        onMismatch: DENY
      PatternLayout:
        pattern: ${logFormat}
      Property:
        - name: bootstrap.servers
          value: ${kafkaBootstrapServers}

    RollingFile:
       name: RollingFile
       fileName: E:/logs/vehicle-server.log
       filePattern: 'logs/vehicle-server.%d{yyyy-MM-dd}.log'
       PatternLayout:
         Pattern: ${logFormat}
       Policies:
         SizeBasedTriggeringPolicy:
           size: 128 MB
    Async:
      - name: AsyncRollingFile
        AppenderRef:
          ref: RollingFile
      - name: AsyncKafka
        AppenderRef:
          ref: Kafka

  Loggers:
      Logger:
        name: org.apache.kafka
        level: info
      Root:
       AppenderRef:
         -  ref: Console
         -  ref: Kafka
         -  ref: AsyncRollingFile
       level: info

