server:
  port: 8201

eureka:
  client:
    serviceUrl:
      defaultZone: http://114.215.80.37:8761/eureka/

  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）

spring:
  application:
    name: vehicle-service
  zipkin:
    base-url: http://114.215.80.37:9411
#  datasource:
#    url: jdbc:mysql://192.168.80.109:3306/oauth?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&failOverReadOnly=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#  #ddl策略
#    jpa:
#      hibernate:
#        ddl-auto: update

jwt:
  header: Authorization
  secret: mySecret
  access_token:
    expiration: 604800
  refresh_token:
    expiration: 604800
  tokenHead: "Bearer "
