server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.90.186:8761/eureka/

  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true
    
spring:
  application:
    name: zuul-service
  zipkin:
    base-url: http://192.168.90.186:9411

auth:
  service-host: http://${auth.host:192.168.90.186}:${server.port}
  service-path: /auth-service
  jwt-token-path: /oauth/jwtToken

zuul:
  # add this because that the gateway receives all header parameters, but the authentication server doesn't.
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    auth-service:
      path: /auths/**
      service-id: auth-service
    part-service:
      path: /parts/**
      service-id: part-service
    hour-service:
      path: /hours/**
      service-id: hour-service
    vehicle-service:
      path: /groups/**
      service-id: vehicle-service
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000